version: "3"
services:
  benchmarkapp:
    image: "nclcloudcomputing/javabenchmarkapp"
    ports:
      - "8080:8080"
  locust-master:
    image: locustio/locust
    ports:
     - "8089:8089"
     - "5557:5557"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --master
  locust-worker:
    image: locustio/locust
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --worker --master-host=10.210.60.57
  mongo:
    image: "mongo"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "/home/student/CSC8110/database:/data/db"
    ports:
      - "27017:27017"
  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:v0.45.0"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rO
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    ports:
      - "8086:8080"
  visualizer:
    image: "dockersamples/visualizer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8088:8080"
